export const EMAIL_FETCH = "EMAIL_FETCH";
export const EMAIL_RESOLVE = "EMAIL_RESOLVE";
export const EMAILS_RESOLVE = "EMAILS_RESOLVE";
export const EMAIL_REJECT = "EMAIL_REJECT";
export const EMAIL_CANCEL = "EMAIL_CANCEL";
