export const HOSPITAL_FETCH = 'HOSPITAL_FETCH';
export const HOSPITAL_RESOLVE = 'HOSPITAL_RESOLVE';
export const HOSPITALS_RESOLVE = 'HOSPITALS_RESOLVE';
export const HOSPITAL_REJECT = 'HOSPITAL_REJECT';
export const HOSPITAL_CANCEL = 'HOSPITAL_CANCEL';
